// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const LOOKUP = new Map([...ALPHABET].map((c, i) => [c, i]));

/**
 * Decodes standard (or URL-safe) base64 to bytes, ignoring whitespace and padding.
 * Used to upload images to Storage from React Native, where Blob/File uploads are unreliable.
 */
export function base64ToBytes(base64: string): Uint8Array {
  const clean = base64.replace(/[\s=]/g, '').replace(/-/g, '+').replace(/_/g, '/');
  if (clean.length % 4 === 1) throw new Error('Invalid base64 length.');
  const out = new Uint8Array(Math.floor((clean.length * 3) / 4));
  let buffer = 0;
  let bits = 0;
  let o = 0;
  for (const ch of clean) {
    const v = LOOKUP.get(ch);
    if (v === undefined) throw new Error(`Invalid base64 character: ${ch}`);
    buffer = (buffer << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out[o++] = (buffer >> bits) & 0xff;
    }
  }
  return out;
}
