#!/usr/bin/env node
// Copies packages/shared/src/*.ts (tests excluded) into supabase/functions/_shared/calorie-shared/
// so Edge Functions import shared code from inside supabase/functions/, which is what
// `supabase functions deploy` bundles. The copies are committed; CI runs `--check`.
//
//   node scripts/sync-shared.mjs          write the copies and delete stale files
//   node scripts/sync-shared.mjs --check  exit 1 and list differences if the copies are stale
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'packages/shared/src');
const DEST = join(ROOT, 'supabase/functions/_shared/calorie-shared');
const HEADER =
  '// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.\n\n';

const check = process.argv.includes('--check');

/** @returns {Map<string, string>} file name -> expected generated content */
function expectedFiles() {
  const files = new Map();
  for (const name of readdirSync(SRC).sort()) {
    if (!name.endsWith('.ts') || name.endsWith('.test.ts')) continue;
    files.set(name, HEADER + readFileSync(join(SRC, name), 'utf8'));
  }
  return files;
}

function existingFiles() {
  return existsSync(DEST) ? readdirSync(DEST).sort() : [];
}

const expected = expectedFiles();
const rel = (p) => relative(ROOT, p);

if (check) {
  const problems = [];
  for (const [name, content] of expected) {
    const path = join(DEST, name);
    if (!existsSync(path)) problems.push(`missing: ${rel(path)}`);
    else if (readFileSync(path, 'utf8') !== content) problems.push(`out of date: ${rel(path)}`);
  }
  for (const name of existingFiles()) {
    if (!expected.has(name)) problems.push(`stale (no source): ${rel(join(DEST, name))}`);
  }
  if (problems.length > 0) {
    console.error(`Shared code copy is out of sync with ${rel(SRC)}:`);
    for (const p of problems) console.error(`  - ${p}`);
    console.error('Run `npm run sync:shared` and commit the result.');
    process.exit(1);
  }
  console.log(`${rel(DEST)} is in sync (${expected.size} files).`);
} else {
  mkdirSync(DEST, { recursive: true });
  let written = 0;
  for (const [name, content] of expected) {
    const path = join(DEST, name);
    if (existsSync(path) && readFileSync(path, 'utf8') === content) continue;
    writeFileSync(path, content);
    written++;
  }
  let removed = 0;
  for (const name of existingFiles()) {
    if (expected.has(name)) continue;
    rmSync(join(DEST, name), { recursive: true, force: true });
    removed++;
  }
  console.log(
    `Synced ${expected.size} files to ${rel(DEST)} (${written} written, ${removed} removed).`,
  );
}
